services:
  odoo:
    extends:
      file: common.yaml
      service: odoo
    build:
      args:
        AGGREGATE: "false"
        PIP_INSTALL_ODOO: "false"
        CLEAN: "false"
        COMPILE: "false"
    environment:
      DOODBA_ENVIRONMENT: "${DOODBA_ENVIRONMENT-devel}"
      LIST_DB: "true"
      PGDATABASE: &dbname devel
      PYTHONDONTWRITEBYTECODE: 1
      SMTP_PORT: "1025"
      ODOO_API_SECRET: "anothersecret"
      INITIAL_LANG: "de_DE"
      BACKEND_URL: "http://127.0.0.1:3000"
      WITHOUT_DEMO: "${DOODBA_WITHOUT_DEMO-all}"
    ports:
      - "127.0.0.1:18069:8069"
      - "127.0.0.1:18072:8072"
    volumes:
      - ./odoo/custom:/opt/odoo/custom:ro,z
      - ./odoo/auto:/opt/odoo/auto:rw,z
      - filestore:/var/lib/odoo:z
    depends_on:
      - db
    command:
      - odoo
      - --limit-memory-soft=0
      - --limit-time-real-cron=9999999
      - --limit-time-real=9999999
      - --workers=0
      - --dev=reload,qweb,werkzeug,xml
      - -i strohm_addon

  db:
    extends:
      file: common.yaml
      service: db
    ports:
      - "127.0.0.1:15432:5432"
    environment:
      POSTGRES_DB: *dbname
      POSTGRES_PASSWORD: odoopassword
      WAN_USERS: '["all"]'
      LAN_USERS: '["all"]'
      WAN_AUTH_METHOD: trust
      LAN_AUTH_METHOD: trust
      HBA_EXTRA_RULES: '["host all all 0.0.0.0/0 trust"]'

#  smtp:
#    extends:
#      file: common.yaml
#      service: smtpfake
#    ports:
#      - "127.0.0.1:8025:8025"
#      - "127.0.0.1:1025:1025"

networks:
  default:
    internal: false
  public:

volumes:
  filestore:
  db:
