name: Build and Push Odoo Image

on:
  push:
    paths:
      - odoo/**
      - .github/workflows/**

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Determine version tag
        id: vars
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            VERSION="${{ github.event.pull_request.title }}"
          elif [[ "${{ github.ref }}" == "refs/heads/main/master" ]]; then
            VERSION="latest"
          else
            VERSION=$(echo "${{ github.ref_name }}" | sed 's/\//-/g')
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./odoo
          push: ${{ github.event_name != 'pull_request' }}
          build-args: |
            - ODOO_VERSION=18.0
            - DEFAULT_REPO_PATTERN="https://github.com/MINcomSmartSolutions/{}.git"
            - DEFAULT_REPO_PATTERN_ODOO="https://github.com/MINcomSmartSolutions/odoo.git"
            - EMAIL="ycs@min2s.com"
            - AGGREGATE=true
            - CLEAN=true
            - COMPILE=true
          tags: mincomsmartsolutions/odoo:${{ env.VERSION }}
