name: Build and Push Odoo Image

on:
  workflow_dispatch:
  repository_dispatch:
    types: [strohm-addon-changed]
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Determine version tag
        id: vars
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            VERSION="${{ github.event.pull_request.title }}"
          elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            VERSION="latest"
          else
            VERSION=$(echo "${{ github.ref_name }}" | sed 's/\//-/g')
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./odoo
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            ODOO_VERSION=18.0
            INITIAL_LANG="de_DE"
            EMAIL="ycs@min2s.com"
            AGGREGATE=true
            CLEAN=true
            COMPILE=true
          tags: |
            ghcr.io/mincomsmartsolutions/odoo:${{ env.VERSION }}
            ghcr.io/mincomsmartsolutions/odoo:18.0
