name: Build and Push Odoo 17 Image

on:
  push:
    paths:
      - odoo/**
      - .github/workflows/**
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./odoo
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            ODOO_VERSION=17.0
            DEFAULT_REPO_PATTERN="https://github.com/MINcomSmartSolutions/{}.git"
            DEFAULT_REPO_PATTERN_ODOO="https://github.com/MINcomSmartSolutions/odoo.git"
            EMAIL="ycs@min2s.com"
            AGGREGATE=true
            CLEAN=true
            COMPILE=true
          tags: ghcr.io/mincomsmartsolutions/odoo:17.0
