name: Build and Push Odoo Image

on:
  push:
    paths:
      - odoo/**

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Image
        working-directory: ./odoo
        run: |
          docker build \
          --build-arg ODOO_VERSION=18.0 \
          --build-arg DEFAULT_REPO_PATTERN="https://github.com/MINcomSmartSolutions/{}.git" \
          --build-arg DEFAULT_REPO_PATTERN_ODOO="https://github.com/MINcomSmartSolutions/odoo.git" \
          --build-arg AGGREGATE=true \
          --build-arg CLEAN=true \
          --build-arg COMPILE=true \
          -t ghcr.io/mincomsmartsolutions/odoo:latest .

      - name: Push Image
        working-directory: ./odoo
        run: |
          docker push ghcr.io/mincomsmartsolutions/odoo:latest
